version: '3.3'

services:
  veloura-next:
    container_name: veloura-next
    restart: always
    image: node:20.10.0
    ports: 
      - 4000:3000
    environment:
      - PORT=3000


    volumes:
      - ./:/usr/src/veloura-next
    working_dir: /usr/src/veloura-next

    networks:
      - client-network


    #FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"
    
networks:
  client-network:
      driver: bridge